#ifndef CGIREADHANDLER_HPP_
#define CGIREADHANDLER_HPP_

#include <sys/epoll.h>
#include <sys/types.h>
#include <sys/wait.h>

#include <vector>

#include "AEventHandler.hpp"
#include "ClientHandler.hpp"
#include "EpollManager.hpp"

/**
 * @class CgiReadHandler
 * @brief Monitors the stdout pipe of a CGI child process asynchronously.
 *
 * Inherits from AEventHandler to read stdout output generated by the CGI child process,
 * parses CGI HTTP headers (including Status), appends the body to the client's output buffer,
 * and transitions the client to WRITING_RESPONSE upon EOF.
 */
class CgiReadHandler : public AEventHandler {
public:
  static const size_t kBufferSize = 65536;
  static const size_t kMaxHeadersSize = 8192;

private:
  EpollManager& epollManager_;
  ClientHandler& client_;
  pid_t cgiPid_;
  std::vector<char> readBuffer_;
  bool headersParsed_;

public:
  CgiReadHandler(int stdout_fd, EpollManager& epoll_manager, ClientHandler& client, pid_t cgi_pid);
  virtual ~CgiReadHandler();

  virtual void onReadReady();
  virtual void onWriteReady();
  virtual void onDisconnect();
};

#endif  // CGIREADHANDLER_HPP_
